In [12]:
# program to modify the dimension of mask file/SKY_MASK_0001.fits

from astropy.io import fits
import numpy as np


# Open the mask image
fits_sky_mask = fits.open('/home/kokoro/NGC5419/SKY_MASK_0001.fits')

print("The dimension of skymask")

data = fits_sky_mask[0].data
dimensions = data.shape
print(data)
print(type(data))
print(dimensions)
info_sky_mask = fits_sky_mask.info()

The dimension of skymask
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(308, 316)
Filename: /home/kokoro/NGC5419/SKY_MASK_0001.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU    1204   (316, 308)   uint8   


In [13]:
# Rotating image
from scipy import ndimage

sky_mask_rotate = ndimage.rotate(data, -80, reshape=True)   # +degrees in clockwise and -degrees in counterclockwise

In [14]:
# Making a new file to write the changed data
hdu = fits.PrimaryHDU(sky_mask_rotate)
hdulist = fits.HDUList([hdu])

hdulist.writeto('ROTATED_SKY_MASK.fits', overwrite=True)
fits_sky_mask.close()

In [15]:
# Checking data of the rotated image
rotated_image = fits.open('ROTATED_SKY_MASK.fits')

info_rotated_image = rotated_image.info()
rotated_data = rotated_image[0].data
dimensions = rotated_data.shape
print(rotated_data)
print(type(rotated_data))
print(dimensions)

rotated_image.close()

Filename: ROTATED_SKY_MASK.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   (358, 365)   uint8   
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(365, 358)
