In [20]:
# program to modify the dimension of skymask

from astropy.io import fits
import numpy as np

# Info for SKY_MASK
fits_sky_mask = fits.open('ROTATED_SKY_MASK.fits')
info_sky_mask = fits_sky_mask.info()


data = fits_sky_mask[0].data
dimensions = data.shape
print(data)
print(type(data))
print(dimensions)

Filename: /ROTATED_SKY_MASK.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   (358, 365)   uint8   
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(365, 358)


In [22]:
# Adding 4 columns in the beginning
for i in range(4):
    data = np.insert(data,0,0,axis=1)
    
# Deleting 5 rows
for j in range(5):
    data = np.delete(data,0,axis=0)

# Check the matrix
print(data)
print(data.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(360, 362)


In [23]:
# Making a new file to write the changed data
hdu = fits.PrimaryHDU(data)
hdulist = fits.HDUList([hdu])

hdulist.writeto('NEW_SKY_MASK_0001.fits', overwrite=True)

fits_sky_mask.close()

In [24]:
# Check the contents in the new file
new_image = fits.open('NEW_SKY_MASK_0001.fits')

info_new_image = new_image.info()
new_data = new_image[0].data
dimensions = new_data.shape
print(new_data)
print(type(new_data))
print(dimensions)

new_image.close()

Filename: NEW_SKY_MASK_0001.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   (362, 360)   uint8   
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(360, 362)


In [25]:
# How many 1 and 0 are there in the array initially(it should be 66303 for 1 and 64017 for 0 initially)
print(len(new_data[new_data==1]))
print(len(new_data[new_data==0]))

66303
64017


In [26]:
# Switch 1 and 0 for elements that 0 or 1 were assigned 
new_data[new_data==1]=99
new_data[new_data==0]=1
new_data[new_data==99]=0

In [27]:
# How many 0 and 1 are there in the array after running the code
# Make sure the number of 1 and 0 match with before running the code
print(len(new_data[new_data==1]))
print(len(new_data[new_data==0]))

64017
66303


In [28]:
# Write the updated data into a new file
hdu = fits.PrimaryHDU(new_data)
hdulist = fits.HDUList([hdu])

hdulist.writeto('FINAL_SKY_MASK_0001.fits', overwrite=True)
new_image.close()

In [29]:
# Check and make sure the info in the new file
image = fits.open('FINAL_SKY_MASK_0001.fits')

info_image = image.info()
data = image[0].data
dimensions = data.shape
print(data)
print(type(data))
print(dimensions)

image.close()

Filename: FINAL_SKY_MASK_0001.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   (362, 360)   uint8   
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
<class 'numpy.ndarray'>
(360, 362)
